-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 13:15:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema БазаЭлектроники
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema БазаЭлектроники
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `БазаЭлектроники` DEFAULT CHARACTER SET utf8 ;
USE `БазаЭлектроники` ;

-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`sensors_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`sensors_table` (
  `sensors_id` INT NOT NULL AUTO_INCREMENT,
  `auduo_moduls` VARCHAR(45) NOT NULL,
  `pressure_sensors` VARCHAR(45) NOT NULL,
  `flow_sensors` VARCHAR(45) NOT NULL,
  `current_sensors` VARCHAR(45) NOT NULL,
  `magnetic_sensors` VARCHAR(45) NOT NULL,
  `Temperature sensors` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sensors_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`opto_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`opto_table` (
  `opto_id` INT NOT NULL AUTO_INCREMENT,
  `displays` VARCHAR(45) NOT NULL,
  `Lasers` VARCHAR(45) NOT NULL,
  `optocouplers` VARCHAR(45) NOT NULL,
  `leds` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`opto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`Mem_stor_device_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`Mem_stor_device_table` (
  `mem_id` INT NOT NULL AUTO_INCREMENT,
  `ic_memory` VARCHAR(45) NOT NULL,
  `memory_modules` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`passivcomp_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`passivcomp_table` (
  `passivcomp_id` INT NOT NULL AUTO_INCREMENT,
  `antennas` VARCHAR(45) NOT NULL,
  `vVaristors` VARCHAR(45) NOT NULL,
  `capacitors` VARCHAR(45) NOT NULL,
  `potentiometers` VARCHAR(45) NOT NULL,
  `resistors` VARCHAR(45) NOT NULL,
  `transformers` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`passivcomp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.` semicond_device_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.` semicond_device_table` (
  `semicond_device_id` INT NOT NULL AUTO_INCREMENT,
  `Processors_controllers` VARCHAR(45) NOT NULL,
  `discrete_Semiconductors` VARCHAR(45) NOT NULL,
  `integrated_circuits` VARCHAR(45) NOT NULL,
  `memory_ic` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`semicond_device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`wires_cables_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`wires_cables_table` (
  `wires_cables_id` INT NOT NULL AUTO_INCREMENT,
  `coaxial_cables_id` VARCHAR(45) NOT NULL,
  `mounting_wire` VARCHAR(45) NOT NULL,
  `flat_cables` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`wires_cables_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`power_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`power_supply` (
  `power_supply_id` INT NOT NULL AUTO_INCREMENT,
  `batteries` VARCHAR(45) NOT NULL,
  `power_supplies` VARCHAR(45) NOT NULL,
  `transformers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`power_supply_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`connectors_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`connectors_table` (
  `connectors_id` INT NOT NULL AUTO_INCREMENT,
  `audio_video_connectors` VARCHAR(45) NOT NULL,
  `terminals` VARCHAR(45) NOT NULL,
  `power_connectors` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`connectors_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`products_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`products_table` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `sensors` VARCHAR(45) NOT NULL,
  `optoelectronics` VARCHAR(45) NOT NULL,
  `Mem_stor_devices` VARCHAR(45) NOT NULL,
  `passiv_component` VARCHAR(45) NOT NULL,
  `semicond_device` VARCHAR(45) NOT NULL,
  `wires_cables` VARCHAR(45) NOT NULL,
  `power_supply` VARCHAR(45) NOT NULL,
  `connectors` VARCHAR(45) NOT NULL,
  `table1_sensors_id` INT NOT NULL,
  `opto_table_opto_id` INT NOT NULL,
  `Mem_stor_device_table_mem_id` INT NOT NULL,
  `passivcomp_table_passivcomp_id` INT NOT NULL,
  ` semicond_device_table_semicond_device_id` INT NOT NULL,
  `wires_cables_table_wires_cables_id` INT NOT NULL,
  `power_supply_power_supply_id` INT NOT NULL,
  `connectors_table_connectors_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_table_table11_idx` (`table1_sensors_id` ASC) VISIBLE,
  INDEX `fk_products_table_opto_table1_idx` (`opto_table_opto_id` ASC) VISIBLE,
  INDEX `fk_products_table_Mem_stor_device_table1_idx` (`Mem_stor_device_table_mem_id` ASC) VISIBLE,
  INDEX `fk_products_table_passivcomp_table1_idx` (`passivcomp_table_passivcomp_id` ASC) VISIBLE,
  INDEX `fk_products_table_ semicond_device_table1_idx` (` semicond_device_table_semicond_device_id` ASC) VISIBLE,
  INDEX `fk_products_table_wires_cables_table1_idx` (`wires_cables_table_wires_cables_id` ASC) VISIBLE,
  INDEX `fk_products_table_power_supply1_idx` (`power_supply_power_supply_id` ASC) VISIBLE,
  INDEX `fk_products_table_connectors_table1_idx` (`connectors_table_connectors_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_table_table11`
    FOREIGN KEY (`table1_sensors_id`)
    REFERENCES `БазаЭлектроники`.`sensors_table` (`sensors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_opto_table1`
    FOREIGN KEY (`opto_table_opto_id`)
    REFERENCES `БазаЭлектроники`.`opto_table` (`opto_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_Mem_stor_device_table1`
    FOREIGN KEY (`Mem_stor_device_table_mem_id`)
    REFERENCES `БазаЭлектроники`.`Mem_stor_device_table` (`mem_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_passivcomp_table1`
    FOREIGN KEY (`passivcomp_table_passivcomp_id`)
    REFERENCES `БазаЭлектроники`.`passivcomp_table` (`passivcomp_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_ semicond_device_table1`
    FOREIGN KEY (` semicond_device_table_semicond_device_id`)
    REFERENCES `БазаЭлектроники`.` semicond_device_table` (`semicond_device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_wires_cables_table1`
    FOREIGN KEY (`wires_cables_table_wires_cables_id`)
    REFERENCES `БазаЭлектроники`.`wires_cables_table` (`wires_cables_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_power_supply1`
    FOREIGN KEY (`power_supply_power_supply_id`)
    REFERENCES `БазаЭлектроники`.`power_supply` (`power_supply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_table_connectors_table1`
    FOREIGN KEY (`connectors_table_connectors_id`)
    REFERENCES `БазаЭлектроники`.`connectors_table` (`connectors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`manufactures_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`manufactures_table` (
  `idmanufactures_table` INT ZEROFILL NOT NULL,
  `ALPS` VARCHAR(45) NOT NULL,
  `Arduino` VARCHAR(45) NOT NULL,
  `BC_Componetnts/Vishay` VARCHAR(45) NOT NULL,
  `Bourns` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmanufactures_table`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`profiles` (
  `profiles_id` INT NOT NULL,
  `buyer` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`profiles_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `БазаЭлектроники`.`main_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `БазаЭлектроники`.`main_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `products` VARCHAR(45) NOT NULL,
  `manufactures` VARCHAR(45) NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `profiles` VARCHAR(45) NOT NULL,
  `manufactures_table_idmanufactures_table` INT ZEROFILL NOT NULL,
  `profiles_profiles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manufactures_table_idmanufactures_table`),
  INDEX `fk_main_table_manufactures_table1_idx` (`manufactures_table_idmanufactures_table` ASC) VISIBLE,
  INDEX `fk_main_table_profiles1_idx` (`profiles_profiles_id` ASC) VISIBLE,
  CONSTRAINT `main_table`
    FOREIGN KEY (`id`)
    REFERENCES `БазаЭлектроники`.`products_table` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_main_table_manufactures_table1`
    FOREIGN KEY (`manufactures_table_idmanufactures_table`)
    REFERENCES `БазаЭлектроники`.`manufactures_table` (`idmanufactures_table`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_main_table_profiles1`
    FOREIGN KEY (`profiles_profiles_id`)
    REFERENCES `БазаЭлектроники`.`profiles` (`profiles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
